language: java

sudo: false 

services:
  - docker 

script: 
  - bash travis_start.sh docker-test1 HelloWorld
  - docker rm $(docker ps -a -q)
  - docker rmi $(docker images -q)
  - docker images -a

after_script: 
  
