language: java

sudo: false 

services:
  - docker 

script: 
  - docker build -f Dockerfile -t test-docker .
  - docker run test-docker 
  - docker images -a
  - docker kill $(docker ps -q)
  - docker images -a


after_script: 
  
